project:
  type: book
  
execute:
  echo: false

book:
  title: "I-15/Main Street Interchange in Payson, Utah"
  author:
    - name: Hayden Atchley
      email: satchley@byu.edu
      # orcid: 0000-0002-0815-3488
      affiliations:
        - ref: byucce
    - name: Matthew Davis
      # email: gregmacfarlane@byu.edu
      # orcid: 0000-0003-3999-7584
      affiliations:
        - ref: byucce
    - name: Adam Hill
      email: hilla25@byu.edu
      # orcid:
      affiliations:
        - ref: byucce
    - name: Sam Runyan
      # email: gregmacfarlane@byu.edu
      # orcid: 0000-0003-3999-7584
      affiliations:
        - ref: byucce
        
  date: today
  date-format: DD MMMM YYYY
  chapters:
    - index.qmd
    - 2_existing.qmd
    - 3_future.qmd
    - 4_matsim.qmd
    - 5_sensitivity.qmd
    - 6_build.qmd
    - 7_conclusions.qmd
    - references.qmd
 
affiliations:
  - id: byucce
    name: Civil and Construction Engineering Department, Brigham Young University
    address: 430 EB
    city: Provo
    state: UT
    postal-code: 84602
    
bibliography:
  - bib/references.bib
  - bib/packages.bib
  - bib/matsim.bib

lof: true
lot: true
fig-align: center

# filters:
#   - acronyms
  
# acronyms:
#   loa_title: ""
#   insert_loa: false
#   insert_links: false
#   include_unused: false
#   sorting: "alphabetical"
#   non_existing: "key"
#   style: "long-short"
#   fromfile:
#     - _acronyms.yml

format:
  # html:
  #   theme: cosmo
  pdf:
    toc-depth: 3
    number-depth: 3
    # template: template.tex
    # mainfont: Gentium Book Basic
    # sansfont: Alte Haas Grotesk
    # monofont: SauceCodePro NF
  # docx:
  #   reference-doc: style/template.docx



