# Introduction

The existing Interstate 15 (I-15) interchange at Main Street in Payson, Utah is under investigation for a potential redesign.
The Main Street interchange is one of two interchanges serving the city of Payson.
It connects I-15 to Main Street, which is classified as a minor arterial [@FuncClass] and carries an Annual Average Daily Traffic (AADT) of 15,000 veh per day [@AADT].

Due to growth and increased travel in the area, the interchange is being investigated for a potential redesign to better serve the Payson and nearby Benjamin, Utah communities.
The Utah Department of Transportation (UDOT) prepared an Environmental Impact Statement in 2019 for the interchange and proposed a series of braided ramps to connect the existing interchange to the proposed Nebo Beltway, just northeast of Main Street [@UDOTStudy].
This study will provide a second evaluation of the existing conditions and potential redesign options for the interchange.


The report consists of six sections.
First, there is discussion of the existing conditions model created using traffic counts and signal timing plans.
Second, there is a proposed redesign with justifications from existing crash data.
Third, growth rates are approximated using the Multi-Agent Transport Simulation (MATSim) modeling package [@MATSim] for future-year scenarios.
Fourth, the models are checked for resiliency under various car-following model parameters.
Fifth, analysis of the future No-Build and Build models is presented.
Finally, there is a summary of key findings and recommendations for future consideration.
